# I don't want to pull several repos just to get a 5 line dead-simple config for each tool
# I would like to be able to define local hooks in .pre-commit-hooks.yaml but that is not possible right now
# See https://github.com/pre-commit/pre-commit/issues/1481
repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true
        files: ^build/
      - id: mypy
        name: mypy (py2)
        entry: mypy
        language: python
        types: [python]
        require_serial: true
        files: ^build/
        args: ['--py2']
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true
        files: ^build/
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        require_serial: true
        files: ^build/
        args: ['--check-only', '--diff']

